VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.name = "puppet"
  end


  config.vm.box = "ubuntu-13.10.-saucy-64"
  config.vm.host_name = "puppet"
  config.vm.network :forwarded_port, guest: 22, host: 2224, id: 'ssh', auto_correct: true
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.synced_folder "../", "/etc/puppet"  
end
